### ISSUE TITLE
Detection of Java/Kryptik.GF

### ISSUE THREAD

**Issue by liberodark** [GlowstoneMC/Glowstone#959] opened 2018-08-05 21:55 UTC
Hi,

All glowstone version downloaded is detected : 
glowstone.jar - une variante de Java/Kryptik.GF cheval de troie.
Please remove your malicious code.

Cordialy

**Comment by aramperes** [comment] 2018-08-05 21:57
Glowstone is open-source, and does not contain any viruses.

If you are concerned about the package you downloaded, consider building Glowstone yourself.

Duplicate of #953.

**Closed as completed by aramperes** 2018-08-05 21:57 UTC
Labels: Priority: duplicate, Priority: wontfix
