### ISSUE TITLE
Chunk Generation Errors

### ISSUE THREAD

**Issue by MrSnowGlobe** [GlowstoneMC/Glowstone#93] opened 2015-09-04 09:56 UTC
Getting Chunk generations when starting the server.

Using Glowstone++ Build #401

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)

Logs - http://pastebin.com/fqEju2zQ

I couldn't post the full log because it exceeds the file size limit of pastebins free offering. I included the start and end of the logs with some middle cut out. 

Will provide full logs if required (:

**Comment by mastercoms** [comment] 2015-09-04 11:05
Thanks for the bug report. I couldn't reproduce this bug, so I am not sure it is fixed with this new version. If it does not fix it, please reopen this issue.

**Closed as completed** 2015-09-04 11:04 UTC

**Comment by MrSnowGlobe** [comment] 2015-09-04 11:46
Thanks for the quick response!

The issue is fixed (:

**Comment by mastercoms** [comment] 2015-09-04 13:44
You're welcome!  I'm glad you reported this bug.

**Comment by TekkitCommando** [comment] 2015-09-04 15:01
Not all plugins are tested to work on Glowstone++ yet, but mastercoms would know the compatibility of plugins generating worlds more then me :P

**Comment by MrSnowGlobe** [comment] 2015-09-04 15:55
Totally understand that Tekkit (:

It's why I am testing a few plugins I use against Glowstone++

**Comment by TekkitCommando** [comment] 2015-09-04 16:09
@MrSnowGlobe How often do you check github?

**Comment by MrSnowGlobe** [comment] 2015-09-04 16:29
Daily. I also get email notifications for issue conversations etc, So I try to respond when I can (: Why?

**Comment by TekkitCommando** [comment] 2015-09-04 17:15
I have a donation system plugin that i wanted to test against glowstone++ in the future, if you are doing exactly that, I was wondering if you would test it for me when its ready :)

**Comment by mastercoms** [comment] 2015-09-04 18:38
I am not sure what causes those errors. I have been trying to figure out for some time now. Could you create a separate issue for it?
