### ISSUE TITLE
Stacktrace on survival, adventure, spectator inventory close

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#101] opened 2015-10-12 01:11 UTC
Java version: 8
OS: Ubuntu 15.04
Glowstone++ version: 1.8.8-SNAPSHOT

**EDIT**: It seems that this only occurs when closing the survival inventory
**EDIT**: Now it occurs on survival, adventure and spectator

When I close my survival inventory the console shows this stack trace (I tried my best to capture it):

```
[SEVERE] Error while handling CloseWindowMessage(id=0) (handler: CloseWindowHandler)
java.lang.IllegalArgumentException: stack amount must be greater than zero
        at org.apache.commons.lang3.Validate.isTrue(Validate.java:155)
        at net.glowstone.entity.GlowHumanEntity.drop(GlowHumanEntity.java:456)
        at net.glowstone.entity.GlowPlayer.drop(GlowPlayer.java:1992)
        at net.glowstone.entity.GlowHumanEntity.closeInventory(GlowHumanEntity.java:395)
        at net.glowstone.net.handler.play.inv.CloseWindowHandler.handle(CloseWindowHandler.java:11)
        at net.glowstone.net.handler.play.inv.CloseWindowHandler.handle(CloseWindowHandler.java:7)
        at com.flowpowered.networking.session.BasicSession.handleMessage(BasicSession.java:80)
        at com.flowpowered.networking.session.BasicSession.messageReceived(BasicSession.java:139)
        at net.glowstone.net.GlowSession.pulse(GlowSession.java:430)
        at net.glowstone.net.SessionRegistry.pulse(SessionRegistry.java:23)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:173)
        at net.glowstone.scheduler.GlowScheduler.access$100(GlowScheduler.java:24)
        at net.glowstone.scheduler.GlowScheduler$2.run(GlowScheduler.java:110)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

```

**Comment by mastercoms** [comment] 2015-10-12 03:33
Did you craft anything?

**Comment by mhsjlw** [comment] 2015-10-12 11:27
@mastercoms No, because you can't craft.

**Comment by z3ntu** [comment] 2015-10-12 11:51
I have this error as well. Completely fresh install, build from website and java version "1.8.0_60"

**Comment by mhsjlw** [comment] 2015-10-12 11:52
@z3ntu Is it only in the survival inventory for you too?

**Comment by z3ntu** [comment] 2015-10-12 11:53
i can check

**Comment by z3ntu** [comment] 2015-10-12 11:54
No, also Adventure & Spectator mode

**Comment by mhsjlw** [comment] 2015-10-12 11:54
Ok, thanks

**Comment by mhsjlw** [comment] 2015-10-12 11:56
I think I know what the problem is, I'll submit a pull request after I test it.

**Comment by mhsjlw** [comment] 2015-10-12 11:57
Yup found the source of the problem here: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/master/src/main/java/net/glowstone/entity/GlowHumanEntity.java#L388

**Comment by mhsjlw** [comment] 2015-10-12 11:57
I guess creative inventory handling is different than survival, adventure etc. etc

**Comment by mhsjlw** [comment] 2015-10-12 12:01
I was wrong. It says the source is this: https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/blob/1faffb66613279cce1db6bef272fa6c57400a2de/src/main/java/net/glowstone/net/message/play/inv/CloseWindowMessage.java

**Comment by mastercoms** [comment] 2015-10-12 12:29
Crafting was working last time I tried. I will see why crafting isn't working now.

**Comment by z3ntu** [comment] 2015-10-12 12:33
Crafting didn't work for me too.

**Comment by TekkitCommando** [comment] 2015-10-12 12:55
Crafting worked for me when i tested it a while back xD, Thats weird :P

**Comment by mastercoms** [comment] 2015-12-30 14:36
Fixed in https://github.com/GlowstonePlusPlus/GlowstonePlusPlus/commit/0be6bc0a5ec62dbf8aa967d831c7a1c47e6536fc

**Closed as completed** 2015-12-30 14:36 UTC
Labels: Priority: major, Category: gameplay feature
