### ISSUE TITLE
Netty 4.1.0.Final Not Working

### ISSUE THREAD

**Issue by garantiertnicht** [GlowstoneMC/Glowstone#286] opened 2016-06-05 18:57 UTC
I downloaded the binary and scorce code, and the versions from the last commit do not work. Instantly after connecting the client and the server shows up that I lost connection and the connection will be closed. Neither the console or the log are giving some useful information, but changing the netty version back seems to resolve the problem.

Nothing interesting, but her's the console output:
20:35:01 [INFORMATION] garantiertnicht [/0:0:0:0:0:0:0:1:51404] connected, UUID: 1f4f35f5-b916-4ee6-83a8-9044ae3b00f2
20:35:01 [INFORMATION] garantiertnicht joined the game
20:35:01 [INFORMATION] garantiertnicht [/0:0:0:0:0:0:0:1:51404] lost connection
20:35:01 [INFORMATION] garantiertnicht left the game

**Comment by mastercoms** [comment] 2016-06-05 23:59
I will see what netty did. Maybe I shouldn't have assumed a release version of a popular network library would be stable.

**Comment by mastercoms** [comment] 2016-06-06 14:32
I reverted back to CR7 for now. I will upgrade to final once I figure out the issue.

**Comment by mastercoms** [comment] 2016-08-16 01:04
The problem is not the switch to PooledByteBufAllocator.

Also, it seems like the connection is randomly dropping. Sometimes the client can send some packets before disconnecting, and very rarely can connect.

**Comment by satoshinm** [comment] 2017-04-13 07:37
Netty has since updated to 4.1.9 (10-Mar-2017), I am using it in another project seems stable, is this still a problem with the latest version?

**Comment by mastercoms** [comment] 2017-04-13 13:34
Yes, this is still a problem with 4.1.9.Final.

**Comment by mastercoms** [comment] 2017-04-13 15:22
Closed in https://github.com/GlowstoneMC/Glowstone/commit/1999ea564596cd8c2d16ab46c21b93762541f228.

**Comment by mastercoms** [comment] 2017-04-16 15:28
Reopening because 199ea5 was reverted due to some regressions in https://github.com/GlowstoneMC/Glowstone/commit/73228f17dd79f8141ea731b5599f64d5a64cbe65.

**Comment by picknchew** [comment] 2017-05-09 21:16
Seems to be an issue with the current version.
I managed to produce a stacktrace. Unsure if related:
```17:13:04 [SEVERE] Error while executing GlowTask{id=1, plugin=null, sync=true: net.glowstone.net.handler.login.EncryptionKeyResponseHandler$ClientAuthCallback$$Lambda$34/1279481276@4f3dc181}
com.flowpowered.network.exception.ChannelClosedException: Trying to send a message when a session is inactive!
        at com.flowpowered.network.session.BasicSession.sendWithFuture(BasicSession.java:89)
        at net.glowstone.net.GlowSession.sendWithFuture(GlowSession.java:393)
        at com.flowpowered.network.session.BasicSession.send(BasicSession.java:103)
        at net.glowstone.entity.GlowPlayer.sendAbilities(GlowPlayer.java:1268)
        at net.glowstone.entity.GlowPlayer.setAllowFlight(GlowPlayer.java:1225)
        at net.glowstone.entity.GlowPlayer.setGameModeDefaults(GlowPlayer.java:1166)
        at net.glowstone.entity.GlowPlayer.join(GlowPlayer.java:355)
        at net.glowstone.net.GlowSession.setPlayer(GlowSession.java:360)
        at net.glowstone.net.handler.login.EncryptionKeyResponseHandler$ClientAuthCallback.lambda$done$0(EncryptionKeyResponseHandler.java:153)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at net.glowstone.scheduler.GlowTask.run(GlowTask.java:167)
        at net.glowstone.scheduler.GlowScheduler.pulse(GlowScheduler.java:152)
        at net.glowstone.scheduler.GlowScheduler.lambda$start$0(GlowScheduler.java:83)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)```

**Comment by mastercoms** [comment] 2017-05-09 23:57
Related. The way we were using idle detection is broken on later versions, we have to find a workaround for it.

**Comment by mastercoms** [comment] 2017-12-11 16:11
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/43a1f78a6927903ab4f6f71760b458e19cf7dd6f.

**Closed as completed by mastercoms** 2017-12-11 16:11 UTC
Labels: Priority: minor, Category: server feature
