### ISSUE TITLE
mc.glowstone.net Outdated Server

### ISSUE THREAD

**Issue by JPVenson** [GlowstoneMC/Glowstone#1009] opened 2019-01-27 11:55 UTC
Hey,

You have stated that you are running a test server under "mc.glowstone.net". I have downloaded the latest minecraft java version "1.12.2" and tried to connect to the test server. That has stated that your server is outdated.

![image](https://user-images.githubusercontent.com/6794763/51800666-d2b07680-2232-11e9-9c99-5ad79dfc6f7d.png)

**Comment by Hagvan** [comment] 2019-01-27 11:57
You are running MC 1.13.2, you need 1.12.2 instead.

**Comment by JPVenson** [comment] 2019-01-27 12:01
@Hagvan 

> **Support for older versions**
> We have taken the decision not to support older versions of Minecraft. We will always try to update to the latest Minecraft version once the Bukkit API is updated.
https://github.com/GlowstoneMC/Glowstone/wiki/Frequently-Asked-Questions#support-for-older-versions

With this note in the FAQ, FMPOV this (bug) might be still a "note" worth.

**Comment by mastercoms** [comment] 2019-01-27 13:42
We haven't updated Glowstone to 1.13 yet (see #957 and the `1.13-hack` branch). This specific problem is not a bug, just a result of another task not being doing, so closing.

**Closed as completed by mastercoms** 2019-01-27 13:42 UTC
Labels: Priority: invalid
