### ISSUE TITLE
Some chunk won't generate proper terrain

### ISSUE THREAD

**Issue by ghost** [GlowstoneMC/Glowstone#896] opened 2018-04-01 02:11 UTC
glowstone-2018.3.0-20180331.081205-37 (Windows10, Java8)

![2018-04-01_10 58 52](https://user-images.githubusercontent.com/37968540/38169152-5decbc3c-359d-11e8-9d72-52a2509e4ad5.png)
![2018-04-01_10 59 06](https://user-images.githubusercontent.com/37968540/38169146-21d555e2-359d-11e8-8547-e666ad50c865.png)
![2018-04-01_11 00 35](https://user-images.githubusercontent.com/37968540/38169147-27613418-359d-11e8-9c1f-e10c2491d074.png)

**Comment by aramperes** [comment] 2018-04-01 02:19
The chunks are generated properly, those "holes" are my poor attempt at cave generation showing off :)

Closing as duplicate of #436, see my [comment](https://github.com/GlowstoneMC/Glowstone/issues/436#issuecomment-365468690) on the problems

**Closed as completed by aramperes** 2018-04-01 02:19 UTC
