### ISSUE TITLE
Server reports "lost connection" right after the player joins

### ISSUE THREAD

**Issue by rrnewton** [GlowstoneMC/Glowstone#288] opened 2016-06-06 13:29 UTC
If I run a server by typing `make` [in this directory](https://github.com/rrnewton/docker-scriptcraft/blob/6aa861ca83fc2ef7c1712f7bc211c4a641cf1518/glowstone%2B%2B_server/), it builds a docker image using this [Dockerfile](https://github.com/rrnewton/docker-scriptcraft/blob/master/glowstone%2B%2B_server/Dockerfile), including glowstone++ 1.9.2.

```
    16:11:05 [INFO] Player [/<X.Y.Z.W>:59916] connected, UUID: <....>
    16:11:05 [INFO] Player joined the game
    16:11:51 [INFO] PlayerX [/<X.Y.Z.W>:59923] lost connection
    16:11:51 [INFO] PlayerX left the game
```

Each time a join attempt is made, this lost-connection error happens.

Any probably causes?

**Comment by mastercoms** [comment] 2016-06-06 14:33
Duplicate of #286. The issue should be fixed now. Please make sure that your source is up to date.

**Closed as completed by mastercoms** 2016-06-06 14:33 UTC
