### ISSUE TITLE
Server keeping the "Starting" status in Pterodactyl Panel

### ISSUE THREAD

**Issue by cybooo** [GlowstoneMC/Glowstone#1109] opened 2021-06-20 02:37 UTC
Title: **Server staying at "Starting" status in Pterodactyl Panel**

Glowstone build: `2021.5.0-SNAPSHOT.5b89f94`

When Glowstone server is started, it still keeps the "Starting" status in Pterodactyl Panel, even when the server is up and running.
![image](https://user-images.githubusercontent.com/57915313/122660356-2f54b900-d181-11eb-83a5-7fc98d17c4c5.png)

Pterodactyl version: 1.3.2

**Comment by merlinlcb** [comment] 2021-06-21 14:30
this is an issue of not properly configuring your pterodactyl egg to detect the right line in console to determine startup, if your using a spigot egg then its looking for the string that comes at the end of startup that says 'done' it does not appear that that same final line is used with glowstone. if you need help with your pterodactyl egg please reach out to their support, its not an issue with glowstone

**Comment by mastercoms** [comment] 2021-06-21 14:58
I think we should work out of the box, since many server providers lock down configuration of their panels.

**Comment by merlinlcb** [comment] 2021-06-21 15:05
the hard part about that would be getting ptero to add an egg for glowstone, if you change the final startup line for glowstone to match that of spigot it would work

**Comment by mastercoms** [comment] 2021-06-21 15:10
Yeah an output change is what I'm thinking. Thanks for identifying the cause of this!

**Comment by merlinlcb** [comment] 2021-06-21 19:07
> Yeah an output change is what I'm thinking. Thanks for identifying the cause of this!

not a problem!

**Comment by mastercoms** [comment] 2021-07-15 00:47
Fixed in https://github.com/GlowstoneMC/Glowstone/commit/1088a05cc0d6d6a57ee9e8d5a97bc024ca761671

**Closed as completed by mastercoms** 2021-07-15 00:47 UTC
