### ISSUE TITLE
Nether Portal Mechanics

### ISSUE THREAD

**Issue by heisluft** [GlowstoneMC/Glowstone#1020] opened 2019-02-07 07:40 UTC
Currently, when right-clicking obsidian with a flint and steel, this is possible:
![2019-02-07_08 33 54](https://user-images.githubusercontent.com/30872344/52396831-84616a00-2ab3-11e9-826f-32c365040289.png)

I will address this in an upcoming pr that will:
- Implement Portal creation (both with flint and steel AND automatic creation when a player first enters the nether)
- Implement Portal related Events

**Comment by VaiTon** [comment] 2019-02-07 15:20
You can use what I've already did in [my branch](https://github.com/VaiTon/Glowstone/tree/nether-portal) if you want!
Also, refer to this previous issue: #130

**Comment by heisluft** [comment] 2019-02-07 18:41
Thank you so much :D will start this on the we so I'm very thankful for any help

**Comment by VaiTon** [comment] 2019-02-08 12:35
You could also use the info provided in this [post](https://www.minecraftforum.net/forums/minecraft-java-edition/survival-mode/294462-nether-portal-science) about how nether portals work. Good coding!

**Comment by heisluft** [comment] 2019-02-08 16:47
Lighting is implemented, players are not yet able to go through them (Have yet to figure out whether Players can't see them yet)

**Comment by aramperes** [comment] 2019-02-09 00:36
Closing as duplicate of #130, please continue the discussion over there.

**Closed as completed by aramperes** 2019-02-09 00:36 UTC
