### ISSUE TITLE
Sound id's not always generated properly

### ISSUE THREAD

**Issue by SHADOWDANCH** [GlowstoneMC/Glowstone#1096] opened 2020-05-08 00:12 UTC
Current [method](https://github.com/GlowstoneMC/Glowstone/blob/dev/src/main/java/net/glowstone/constants/GlowSound.java#L36) of generating minecraft sound id from `Sound` bukkit enum not always working correctly. For example unable to play shulker open sound because it contains `_` in middle part of the name and instead `block.shulker_box.open` we will get `block.shulker.box.open`

**Comment by mastercoms** [comment] 2020-05-25 15:59
Good catch, I guess we can add an exceptions list + tests? I think it works well for the majority and saves time. Not sure where we can get a list of valid vanilla names though for tests.

**Comment by mastercoms** [comment] 2021-07-15 00:51
We're considering using https://github.com/Articdive/ArticData for this.

**Comment by mastercoms** [comment] 2021-07-15 01:23
Duplicate of #519.

**Closed as completed by mastercoms** 2021-07-15 01:23 UTC
Labels: Priority: duplicate
